site_name: Root docs
repo_url: https://github.com/ankitggits/backstage-demo
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - Local development: local-development.md
  - Feature Testing: feature-testing.md
  - Mermaiding: mermaiding-er-diag.md
  - Different Mermain: mermaid-diagram-test1.md
  - TestDoc: test-doc.md
  - Embedded Lucid Chart: testing-lucid.md
  - Subdirectory docs: "!include ./sub-dir-documentation/mkdocs.yml"
  - Runbook: runbook.md
  - Images: images.md

docs_dir: docs
plugins:
  - techdocs-core

